spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.103.115:8848
      config:
        server-addr: 101.42.103.115:8848  # HTTP端口用于配置管理

server:
  port: 8081

dubbo:
  consumer:
    serialization: fastjson2  # 消费者也使用Fastjson2
    check: false  # 启动时不检查服务提供者是否存在