spring:
  application:
    name: uav-gateway-iot

dubbo:
  registry:
    address: nacos://192.168.126.128:8848
  consumer:
    check: false  # 启动时不检查服务可用性，避免因uav-service未启动而失败
    timeout: 5000  # 设置调用超时时间