spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.103.115:8848
      config:
        server-addr: 101.42.103.115:8848  # HTTP端口用于配置管理

kafka:
  uav:
    telemetry:
      topic: uav-telemetry

dubbo:
  scan:
    base-packages: com.uav.gateway.impl
  protocol:
    name: tri
    port: -1  # 随机端口
    serialization: fastjson2  # 使用Fastjson2序列化
  registry:
    address: nacos://101.42.103.115:8848
  consumer:
    serialization: fastjson2  # 消费者也使用Fastjson2
    check: false  # 启动时不检查服务提供者是否存在
  provider:
    serialization: fastjson2  # 提供者也使用Fastjson2
  qos:
    port: 22223  # 修改QoS端口为22223，避免冲突
    accept-foreign-ip: true  # 允许远程访问QoS